# PARAMETERS TO CONTROL THE BEHAVIOR OF THE GAME ENGINE
# DO NOT REMOVE OR RENAME THIS FILE
PLAYER_1_NAME = "A"
# Point each player path at a Python bot directory with commands.json
PLAYER_1_PATH = "./python_skeleton"
# NO TRAILING SLASHES ARE ALLOWED IN PATHS
PLAYER_2_NAME = "B"
PLAYER_2_PATH = "./check_call_bot"
# GAME PROGRESS IS RECORDED HERE
GAME_LOG_FILENAME = "gamelog"
# OUTPUT DIRECTORY FOR ENGINE LOG FILES
RESULTS_DIR = "./results/"
# PLAYER_LOG_SIZE_LIMIT IS IN BYTES
PLAYER_LOG_SIZE_LIMIT = 524288
# STARTING_GAME_CLOCK AND TIMEOUTS ARE IN SECONDS
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 180.0
BUILD_TIMEOUT = 10.0
CONNECT_TIMEOUT = 10.0
# MATCH PARAMETERS (Aligned with 2026 Tournament Rules)
NUM_ROUNDS = 300
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1

PLAYER_TIMEOUT = 60
